# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Seattle Prep Class of 2006 | 10th Reunion
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Alex Korbonits '06 and Mick Newell '06
email: SeattlePrepClassOf2006@gmail.com
facebook_username: SeattlePrepAlumni
twitter_username: korbonits 
github_username: SeattlePrepClassOf2006

address:
  - line: "4301 Leary Way NW, Seattle, WA 98107"

telephone: (206) 818-1458
copyright:

# API settings
google_api_key: AIzaSyD0K7qHBt-Jvfdm6HruX-ozGUMWbMimFCo

# Build settings
markdown: kramdown

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site